"""user external_id

Revision ID: d9ff1b149d91
Revises: 7aef26cd4122
Create Date: 2026-07-19 15:10:08.001393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9ff1b149d91'
down_revision: Union[str, Sequence[str], None] = '7aef26cd4122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_external_id'), 'user', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_external_id'), table_name='user')
    op.drop_column('user', 'external_id')
    # ### end Alembic commands ###
